"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.transcribeWithWhisper = transcribeWithWhisper;
const child_process_1 = require("child_process");
const path_1 = __importDefault(require("path"));
const promises_1 = __importDefault(require("fs/promises"));
async function transcribeWithWhisper(audioPath, options) {
    const { language = 'auto', model = 'base', onProgress, onLog } = options;
    const outputDir = path_1.default.dirname(audioPath);
    const fileNameNoExt = path_1.default.basename(audioPath, path_1.default.extname(audioPath));
    const jsonPath = path_1.default.join(outputDir, `${fileNameNoExt}.json`);
    const pythonBin = 'python';
    // Improvements for CPU speed and accuracy per instructions
    const commandArgs = [
        '-m', 'whisper',
        audioPath,
        '--model', model,
        '--output_format', 'json',
        '--output_dir', outputDir,
        '--beam_size', '5',
        '--temperature', '0',
        '--fp16', 'False',
        '--word_timestamps', 'True'
    ];
    if (language && language !== 'auto') {
        commandArgs.push('--language', language);
        if (language === 'hi') {
            commandArgs.push('--initial_prompt', 'नमस्ते, आप कैसे हैं? यह हिंदी देवनागरी लिपि है।');
        }
    }
    return new Promise((resolve, reject) => {
        const whisper = (0, child_process_1.spawn)(pythonBin, commandArgs, {
            shell: false,
            env: {
                ...process.env,
                PYTHONIOENCODING: 'utf-8',
                PYTHONUTF8: '1',
            }
        });
        whisper.stdout.on('data', (data) => {
            if (onLog)
                onLog(data.toString());
            if (onProgress)
                onProgress(0.1);
        });
        whisper.stderr.on('data', (data) => {
            const logMsg = data.toString();
            if (onLog)
                onLog(logMsg);
            if (logMsg.includes('-->') && onProgress)
                onProgress(0.5);
        });
        whisper.on('error', (err) => {
            if (onLog)
                onLog(`[ERROR] Whisper process error: ${err.message}`);
            reject(new Error(`Whisper Error: ${err.message}`));
        });
        whisper.on('close', async (code) => {
            if (code !== 0) {
                return reject(new Error(`Whisper process exited with code ${code}`));
            }
            if (onProgress)
                onProgress(1);
            try {
                const exists = await promises_1.default.access(jsonPath).then(() => true).catch(() => false);
                if (exists) {
                    const content = await promises_1.default.readFile(jsonPath, 'utf-8');
                    const parsed = JSON.parse(content);
                    if (!parsed.segments || parsed.segments.length === 0) {
                        throw new Error("Transcribed audio was empty or silent.");
                    }
                    const duration = parsed.duration || parsed.segments[parsed.segments.length - 1]?.end || 0;
                    const segments = parsed.segments.map((s) => ({
                        start: Number(s.start.toFixed(2)),
                        end: Number(s.end.toFixed(2)),
                        text: s.text ? s.text.trim() : ""
                    }));
                    resolve({
                        language: parsed.language || language || "en",
                        duration,
                        segments
                    });
                }
                else {
                    reject(new Error("No output generated by Whisper."));
                }
            }
            catch (e) {
                reject(e);
            }
        });
    });
}
//# sourceMappingURL=whisper.js.map