import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs/promises';

export interface WhisperOptions {
    language?: string;
    model?: string;
    scriptMode?: string;
    onProgress?: (progress: number) => void;
    onLog?: (log: string) => void;
}

export interface ASRResult {
    language: string;
    duration: number;
    segments: Array<{ start: number; end: number; text: string }>;
}

export async function transcribeWithWhisper(audioPath: string, options: WhisperOptions): Promise<ASRResult> {
    const { language = 'auto', model = 'base', scriptMode, onProgress, onLog } = options;
    const outputDir = path.dirname(audioPath);
    const fileNameNoExt = path.basename(audioPath, path.extname(audioPath));
    const jsonPath = path.join(outputDir, `${fileNameNoExt}.json`);

    const pythonBin = 'python';

    // Improvements for CPU speed and accuracy per instructions
    const commandArgs = [
        '-m', 'whisper',
        audioPath,
        '--model', model,
        '--output_format', 'json',
        '--output_dir', outputDir,
        '--beam_size', '5',
        '--temperature', '0',
        '--fp16', 'False',
        '--word_timestamps', 'True'
    ];

    if (language && language !== 'auto') {
        let finalLanguage = language;
        if (scriptMode === 'Romanized' || scriptMode === 'Mixed' || language === 'hinglish') {
            // Must force 'en' language track to get Latin characters from Whisper for Hindi audio
            finalLanguage = 'en';
            commandArgs.push('--initial_prompt', 'Transcribe exactly in Romanized Hindi / Hinglish. Use the English alphabet only. Do NOT use Devanagari script. Maintain the Hindi meaning.');
        } else if (language === 'hi') {
            finalLanguage = 'hi';
            commandArgs.push('--initial_prompt', 'नमस्ते, आप कैसे हैं? यह हिंदी देवनागरी लिपि है।');
        }

        if (finalLanguage === 'hinglish') finalLanguage = 'hi';
        commandArgs.push('--language', finalLanguage);
    }

    return new Promise((resolve, reject) => {
        const whisper = spawn(pythonBin, commandArgs, {
            shell: false,
            env: {
                ...process.env,
                PYTHONIOENCODING: 'utf-8',
                PYTHONUTF8: '1',
            }
        });

        whisper.stdout.on('data', (data) => {
            if (onLog) onLog(data.toString());
            if (onProgress) onProgress(0.1);
        });

        whisper.stderr.on('data', (data) => {
            const logMsg = data.toString();
            if (onLog) onLog(logMsg);
            if (logMsg.includes('-->') && onProgress) onProgress(0.5);
        });

        whisper.on('error', (err) => {
            if (onLog) onLog(`[ERROR] Whisper process error: ${err.message}`);
            reject(new Error(`Whisper Error: ${err.message}`));
        });

        whisper.on('close', async (code) => {
            if (code !== 0) {
                return reject(new Error(`Whisper process exited with code ${code}`));
            }

            if (onProgress) onProgress(1);

            try {
                const exists = await fs.access(jsonPath).then(() => true).catch(() => false);
                if (exists) {
                    const content = await fs.readFile(jsonPath, 'utf-8');
                    const parsed = JSON.parse(content);
                    
                    if (!parsed.segments || parsed.segments.length === 0) {
                        throw new Error("Transcribed audio was empty or silent.");
                    }

                    const duration = parsed.duration || parsed.segments[parsed.segments.length - 1]?.end || 0;
                    const segments = parsed.segments.map((s: any) => ({
                        start: Number(s.start.toFixed(2)),
                        end: Number(s.end.toFixed(2)),
                        text: s.text ? s.text.trim() : ""
                    }));

                    resolve({
                        language: parsed.language || language || "en",
                        duration,
                        segments
                    });
                } else {
                    reject(new Error("No output generated by Whisper."));
                }
            } catch (e: any) {
                reject(e);
            }
        });
    });
}
